spring.application.name=ai

logging.pattern.console=%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) -%msg%n

spring.ai.openai.api-key=${OPENAI_API_KEY}

# tell spring which chat model to use by default
#spring.model.ai.chat=ollama

# tells spring which chat model we are running in our local system
spring.ai.ollama.chat.model=llama3.2

#ENABLE DEBUG LEVEL LOG FOR ADVISOR
logging.level.org.springframework.ai.chat.client.advisor=DEBUG

#H2-DB connection properties
spring.datasource.url=jdbc:h2:file:D:\\Repo\\H2_DB;AUTO_SERVER=true
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=scott
spring.datasource.password=tiger

spring.ai.chat.memory.repository.jdbc.initailize-schema=always
#spring.ai.chat.memory.repository.jdbc.schema=classpath:D:\\Repo\\SpringAI_integrated_with_LLMs\\src\\main\\resources\\schema

#Qdrant docker compose setup
spring.docker.compose.stop.command=down
#initailize the schema when the DB is created.
spring.ai.vectorstore.qdrant.initailize-schema=true
spring.ai.vectorstore.qdrant.host=localhost

#spring used gRPC protocol to communicate with DB
spring.ai.vectorstore.qdrant.port=6334
spring.ai.vectorstore.qdrant.collection-name=zam-zam