spring.application.name=ai

logging.pattern.console=%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) -%msg%n

spring.ai.openai.api-key=${OPENAI_API_KEY}

# tell spring which chat model to use by default
#spring.model.ai.chat=ollama

# tells spring which chat model we are running in our local system
spring.ai.ollama.chat.model=llama3.2

#ENABLE DEBUG LEVEL LOG FOR ADVISOR
logging.level.org.springframework.ai.chat.client.advisor=DEBUG